### ISSUE TITLE
LICENSE is missing

### ISSUE THREAD

**Issue by deepy** [elevennl/gradle-node-plugin#3]
Heyo,

Since this contains code from srs and node-gradle it'd be great if you could keep the LICENSE file intact [https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0))

**Comment by Shuyinsama** [comment]
Yes you are right! Cleaned up too much during forking :)
I pushed a commit with the License https://github.com/elevennl/gradle-node-plugin/blob/master/LICENSE

I've also updated the README with a notice at the top of the file what the purpose for this fork was.
